### ISSUE TITLE
Error while try to start game

### ISSUE THREAD

**Issue by Nick222** [widelands/wl_addons_server#138] opened 2022-06-15 09:27 UTC
Xubuntu 22.04
Widelands 1.0
Europeans Tribe 2.9.9+122

When I try to start any game (except random) - I see error-window:

> Error while loading tribe '* (any tribe)':
> Description manager::register_description: Attempt to register description name: 'barleyfield_harvested' script 'tribes/immovables/barleyfield/harvested/init.lua'
> but the object has already been registered to script: 'addons/europeans_tribe.wad/immovables/barleyfield/harvested/init.lua'

and game did not start.

**Comment by matthiakl** [comment] 2022-06-15 15:20
Duplicate of #136

> Starting with 3.0.0 the issue is solved.
https://github.com/widelands/wl_addons_server/issues/136#issuecomment-1154161828

Leaving this open until 3.0.0 has been published.

**Comment by Nick222** [comment] 2022-06-17 13:14
Now

> Error while loading tribe 'europeans': [./src/scripting/lua_errors.cc:22] tribe europeans: Failed adding immovable 'ryefield_tiny': DescriptionManager::load_description: Object 'ryefield_tiny' was not registered

**Comment by MarkMcWire** [comment] 2022-06-18 13:37
Solved in 3.0.1.

**Closed** 2023-01-19 12:49 UTC
Labels: duplicate
