### ISSUE TITLE
List format

### ISSUE THREAD

**Issue by matthiakl** [widelands/wl_addons_server#4] opened 2021-01-09 16:57 UTC
When the addon system receives more user content, the list format should be refactored. It looks like the UpdateList tool produces a large diff, when a new addon is added. This can cause merge problems.

**Comment by Noordfrees** [comment] 2021-01-09 17:08
As far as I can see there are two changes that need fixing:
First, the timestamps of all POT files are updated. This is unnecessary and could be fixed by pulling the i18n maintenance into a separate script that is run only on master but not on feature branches.
The second issues are the enormous changes to `list`, which are caused by Java's `File.listFiles()` listing the files in arbitrary order. This can be solved by sorting the result alphabetically.

**Closed** 2021-01-09 17:24 UTC
Labels: maintenance
